// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6J6MbYSr9rObqsD86EPzL_pkvMtf0XI',
    appId: '1:58678904413:web:4592e32de0f0e0d729afb4',
    messagingSenderId: '58678904413',
    projectId: 'ecommerce-mad-7bd1b',
    authDomain: 'ecommerce-mad-7bd1b.firebaseapp.com',
    storageBucket: 'ecommerce-mad-7bd1b.firebasestorage.app',
    measurementId: 'G-407JVQLMY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDof9IoCsZw8D6bpjrvh7En7BoWxkR2Kh8',
    appId: '1:58678904413:android:28d19da862511d9929afb4',
    messagingSenderId: '58678904413',
    projectId: 'ecommerce-mad-7bd1b',
    storageBucket: 'ecommerce-mad-7bd1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKa5kSe5AfffdbjYZQo1Eh9OGpv1kih5M',
    appId: '1:58678904413:ios:6eb634014bb8726729afb4',
    messagingSenderId: '58678904413',
    projectId: 'ecommerce-mad-7bd1b',
    storageBucket: 'ecommerce-mad-7bd1b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKa5kSe5AfffdbjYZQo1Eh9OGpv1kih5M',
    appId: '1:58678904413:ios:6eb634014bb8726729afb4',
    messagingSenderId: '58678904413',
    projectId: 'ecommerce-mad-7bd1b',
    storageBucket: 'ecommerce-mad-7bd1b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
